name: mini_product_catalog_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  skeletonizer: ^1.4.3

  # Navigation & State Management
  go_router: ^14.7.2
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3

  # Networking & Storage
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  flutter_cache_manager: ^3.4.1
  custom_refresh_indicator: ^4.0.1

  # Database & Local Storage
  hive: ^2.2.3
  hive_generator: ^2.0.1

  # Firebase Services
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4

  # Code Generation & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.9.0

  # Logging & Utilities
  logger: ^2.5.0
  equatable: ^2.0.7

  # Testing
  mockito: ^5.4.5
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Generation
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/data/
