// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVy30x6Y5BhFAypDewYjtjX80a1TLRiG0',
    appId: '1:781966192077:web:08b4a78a52147b57bfe884',
    messagingSenderId: '781966192077',
    projectId: 'mini-product-catalog-app',
    authDomain: 'mini-product-catalog-app.firebaseapp.com',
    storageBucket: 'mini-product-catalog-app.firebasestorage.app',
    measurementId: 'G-LVXL8E554Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn7WddwV0RGfYhiRJOT0damA0LL3pNU14',
    appId: '1:781966192077:android:5bd08a131d78c230bfe884',
    messagingSenderId: '781966192077',
    projectId: 'mini-product-catalog-app',
    storageBucket: 'mini-product-catalog-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ-TYXov37eZF5qlynQa9KY_2DmYAgY7E',
    appId: '1:781966192077:ios:76fa774b5c96c7dcbfe884',
    messagingSenderId: '781966192077',
    projectId: 'mini-product-catalog-app',
    storageBucket: 'mini-product-catalog-app.firebasestorage.app',
    iosBundleId: 'com.example.miniProductCatalogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ-TYXov37eZF5qlynQa9KY_2DmYAgY7E',
    appId: '1:781966192077:ios:76fa774b5c96c7dcbfe884',
    messagingSenderId: '781966192077',
    projectId: 'mini-product-catalog-app',
    storageBucket: 'mini-product-catalog-app.firebasestorage.app',
    iosBundleId: 'com.example.miniProductCatalogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVy30x6Y5BhFAypDewYjtjX80a1TLRiG0',
    appId: '1:781966192077:web:fe95648df19533c3bfe884',
    messagingSenderId: '781966192077',
    projectId: 'mini-product-catalog-app',
    authDomain: 'mini-product-catalog-app.firebaseapp.com',
    storageBucket: 'mini-product-catalog-app.firebasestorage.app',
    measurementId: 'G-RDE9NMNREC',
  );

}